### ISSUE TITLE
enclosure-duration: should be defined as length in seconds

### ISSUE THREAD

**Issue by karstenw** [cisene/RSS-3.0#2]
which goes along nice with existing itunes data and podcasting 2.0 database.

**Comment by cisene** [comment]
The specification says "A value of whole seconds in Base10 format or colon-separated values in order Hours, minutes, seconds (hh:mm:ss)" .. so an unsigned integer value is valid as well as HH:mm:ss -- the last is best as human-readable/presentation but the number of seconds should be used internally during processing.
